### ISSUE TITLE
Replace hardcoded dates with default range based on today

### ISSUE THREAD

**Issue by nikolastojkov** [whoeverest/nlbcli#10]
There are still hardcoded dates for requesting transaction balance (between dates).

**Comment by whoeverest** [comment]
By default, the NLBKlik UI sets a 30 day range, that ends today (on any given day). We should replicate that behavior as a default.

**Comment by whoeverest** [comment]
Fixed with https://github.com/whoeverest/nlbcli/commit/8f6d7c73d8621fcf7160b5345329407ecbf4c4ff
