### ISSUE TITLE
Login command inconsistent return

### ISSUE THREAD

**Issue by nikolastojkov** [whoeverest/nlbcli#13]
Inconsistent returns in the login command. 

This may be okay for normal CLI usage, but if you're trying to use it in an API or another project, it will help a lot to have a JSON output for the login command as well.

## Issue
If you try and login with bogus login information, you get a whole trace of the error:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/bin/nlbcli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/nlbcli/__main__.py", line 24, in main
    login_and_save_credentials(username, password)
  File "/usr/local/lib/python3.9/site-packages/nlbcli/session.py", line 82, in login_and_save_credentials
    new_session = _login(username, password)
  File "/usr/local/lib/python3.9/site-packages/nlbcli/session.py", line 49, in _login
    raise Exception(response_msg)
Exception: Неправилно корисничко име или лозинка
```
But if you do it successfully:
```
Info: logged in successfully; saved credentials and session data.
```

Different return styles, different languages, etc.

## Solution
Return a simple JSON response.
#### If successful 
```
{
    "error": false,
    "message": "Successfully logged in"
}
```
#### If failed
```
{
    "error": true,
    "message": "Invalid credentials"
}
````

**Comment by whoeverest** [comment]
That message is intended to be read by humans, or digested in logs, so the JSON format isn't suitable.

There's one thing I agree with: we shouldn't print an exception in case of an invalid password, so I'll change it to print a normally formated log message, and exit with a 1. As for making it a JSON, I don't plan on doing that.

**Comment by whoeverest** [comment]
Output is consistent after 8b86bc3, closing.
